### ISSUE TITLE
[feature/donate] 후원 정보 수렴 기능 개발

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#11]
# 1. TODO
- [x] DonateController
- [x] 후원 정보를 입력받는 endpoint
- [x] 후원 정보 저장 기능 제공하는 DonateService
- [x] DonateRepository

---

# 2. Test Case
## 2.1. DonateControllerTest
- [x] 올바른 값 입력받고 올바른 상태 반환하는지 테스트

## 2.2. DonateServiceTest
- [x] Repository 잘 호출하는지 테스트

## 2.3. DonateRepositoryTest
- [x] 데이터 잘 입력되는지 테스트

---

# 3. 유의사항
- Notion 문서 참고
