### ISSUE TITLE
[Controller] 연주회 정보 제공 기능 개발

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#12]
# 1. TODO
- [ ] ConcertController 생성
- [ ] GET 가장 최근 정기연주회 제공 endpoint
- [ ] GET 연주회 정보 요약 list 제공하는 endpoint
- [ ] GET 연주회 하나에 대한 상세 정보 제공하는 endpoint
- [ ] ConcertService
- [ ] ConcertRepository

---

# 2. Test Case
## 2.1. ConcertControllerTest
- [ ] 최근 정기연주회 제공 endpoint
- [ ] 연주회 정보 요약 list endpoint
- [ ] 연주회 상세정보 endpoint
- [ ] 실패 테스트

## 2.2. ConcertServiceTest
- [ ] 각 method마다 올바른 값 반환하는지 테스트
- [ ] 연주회 정보 요약 잘못된 파라미터 에 대한
- [ ] 그 외 실패 테스트

## 2.3. ConcertRepositoryTest
- [ ] 값 조회 테스트

---

# 3. 유의사항
- Notion 문서 참고
- 정보 요약 list endpoint는 scheme를 parameter로 받음. 일단 summary가 아닌 경우 모두 잘못된 입력으로 간주
- 값이 없을 시 summary로 설정
