### ISSUE TITLE
[feature/member] ClubMember 정보 제공, 저장하는 기능 개발

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#14]
# 1. TODO
- [x] 유저 정보 제공하는 endpoint : `user_type` parameter에 따라 다른 기능 제공
- [x] member인 경우 모든 단원(+회장단)에 대한 리스트
- [x] manager인 경우 회장단 3명의 정보만 제공
- [x] MemberService
- [x] MemberRepository
---

# 2. Test Case
## 2.1. MemberControllerTest
- [x] 파라미터에 대해 올바른 값을 넘겨주는지 테스트
- [x] 잘못된 `user_type`에 대해 실패 테스트

## 2.2. MemberServiceTest
- [x] 입력에 대해 올바른 값을 반환하는지 테스트

---

# 3. 유의사항
- Notion 문서 참고하여 개발
