### ISSUE TITLE
[Repository] FAQRepository 생성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#20]
# 1. TODO
- [x] FAQRepository 생성
- [x] Test Code 작성

---

# 2. Test Case
## 2.1. FAQRepositoryTest
- [x] 1개의 값이 잘 저장되고 조회되는지 테스트
- [x] 2개 이상의 값을 저장하면 개수에 맞게 잘 저장되는지 테스트
- [x] @NotNull어노테이션이 붙은 필드를 null로 설정하고 저장하면 Exception이 발생하는지 테스트

---

# 3. 유의사항
- 반드시 saveAndFlush() 메서드로 저장하여 테스트 할 것
