### ISSUE TITLE
[Domain] @NotNull annotation library 수정

### ISSUE THREAD

**Issue by AllyHyeseongKim** [cau-rubato/rubato-backend#22]
# 1. TODO
## 1.1. Dependency
- [x]  Add the dependency: `org.springframework.boot:spring-boot-starter-validation`
## 1.2. Change the `@NotNull` annotation library from `com.sun.istack.NotNull` to `javax.validation.constraints.NotNull`
- [x]  `Manager.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Manager.java#L3
- [x]  `domain/FAQ.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/FAQ.java#L3
- [x]  `domain/Donate.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Donate.java#L3
- [x]  `domain/Department.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Department.java#L3
- [x]  `domain/Budget.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Budget.java#L3
- [x]  `domain/ApplyCampaign.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/ApplyCampaign.java#L3
- [x]  `domain/Apply.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Apply.java#L3
- [x]  `domain/Account.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Account.java#L3
- [x]  `domain/type/Address.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/type/Address.java#L3
- [x]  `domain/type/Experience.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/type/Experience.java#L3
- [x]  `domain/type/Location.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/type/Location.java#L3
- [x]  `domain/member/Applicant.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/member/Applicant.java#L3
- [x]  `domain/member/ClubMember.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/member/ClubMember.java#L3
- [x]  `domain/member/GuestMember.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/member/GuestMember.java#L3
- [x]  `domain/member/Member.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/member/Member.java#L3
- [x]  `domain/mapping/ApplicantExperience.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/ApplicantExperience.java#L3
- [x]  `domain/mapping/ConcertPamphlet.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/ConcertPamphlet.java#L3
- [x]  `domain/mapping/DonateBudget.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/DonateBudget.java#L3
- [x]  `domain/mapping/MemberInstrument.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/MemberInstrument.java#L3
- [x]  `domain/mapping/concertMember/ClubConcertMember.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ClubConcertMember.java#L3
- [x]  `domain/mapping/concertMember/concertMember.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ConcertMember.java#L3
- [x]  `domain/mapping/concertMember/GuestConcertMember.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/GuestConcertMember.java#L3
- [x]  `domain/concert/Concert.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/concert/Concert.java#L3
- [x]  `domain/concert/RegularConcert.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/concert/RegularConcert.java#L3
## 1.3. Remove `@NotNull` annotation of CreatedAt, ModifiedAt attributes
- [x]  `Manager.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Manager.java#L41-L46
- [x]  `domain/FAQ.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/FAQ.java#L26-L31
- [x]  `domain/Donate.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Donate.java#L34-L39
- [x]  `domain/Department.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Department.java#L34-L39
- [x]  `domain/Budget.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Budget.java#L30-L35
- [x]  `domain/ApplyCampaign.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/ApplyCampaign.java#L37-L42
- [x]  `domain/Apply.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Apply.java#L45-L50
- [x]  `domain/Account.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/Account.java#L37-L42
- [x]  `domain/type/Location.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/type/Location.java#L34-L39
- [x]  `domain/member/Member.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/member/Member.java#L51-L56
- [x]  `domain/mapping/ConcertPamphlet.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/ConcertPamphlet.java#L34-L39
- [x]  `domain/mapping/MemberInstrument.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/MemberInstrument.java#L31-L36
- [x]  `domain/mapping/concertMember/concertMember.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ConcertMember.java#L48-L53
- [x]  `domain/concert/Concert.java`
https://github.com/cau-rubato/rubato-backend/blob/7ad779850b9e2ac5f6d10c5b2c67d1b6c1074d80/src/main/java/org/rubatophil/www/api/domain/concert/Concert.java#L48-L53
## 1.4. modifiedAt, createdAt attribute 누락
- [x]  `domain/mapping/ApplicantExperience.java`
- [x]  `domain/mapping/DonateBudget.java`
---

# 2. Test Case
_해당사항 없음_

---

# 3. 유의사항
_해당사항 없음_
