### ISSUE TITLE
[Domain] Concert, RegularConcert 수정 및 Test Code 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#29]
# 1. TODO
## 1.1. Concert
- [x] `Setter` 설정 필드 제한
- [x] `Constructor`생성
- [x] `@NoArgsConstructor` 어노테이션 추가 후 `AccessLevel.PROTECTED` 설정
- [x] `addConcertMember()` 메소드 생성
- [x] `addConcertPamphlet()` 메소드 생성
- [ ] `addConcertPIece()` 메소드 생성

## 1.2. RegularConcert
- [x] `Constructor`생성
- [x] `Constructor`에 `Builder` 설정
- [x] `@NoArgsConstructor` 어노테이션 추가 후 `AccessLevel.PROTECTED` 설정

---

# 2. Test Case
## 2.1. Concert
- [x] `addConcertMember()` 테스트
- [x] `addConcertPamphlet()` 테스트

## 2.2. RegularConcert
- [x] `Builder` 테스트
- [x] `addConcertPiece()` 테스트
---

# 3. 유의사항
- em.persist 이용하여 테스트
- `Builder` 테스트 시 preprsist가 잘 적용되는지 테스트
- add 메소드 테스트 시 실패 테스트도 반드시 할 것
- `Setter`와 `Builder`는 허용할 필드를 잘 고려해서 넣을 것.
  - 이미 초기화되고, 불변값을 가지는 필드는 `Builder` 허용하지 않음.
  - 수정하면 안되는 필드에 대해서 `Setter`허용하지 않음.
  - 이 외 필드의 특성에 따라 잘 판단하여 `Setter`, `Builder`를 허용하지 결정
- add 메서드는 연관관계 양쪽 클래스 모두 업데이트 해야함.
