### ISSUE TITLE
[Domain] Convert Parent Classes to Abstract Class

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#30]
# 1. TODO
- [x] Concert https://github.com/cau-rubato/rubato-backend/blob/7e0e25634c53e5a9f80e813643bdb8c05f17bd46/src/main/java/org/rubatophil/www/api/domain/concert/Concert.java#L21
- [x] Member https://github.com/cau-rubato/rubato-backend/blob/7e0e25634c53e5a9f80e813643bdb8c05f17bd46/src/main/java/org/rubatophil/www/api/domain/member/Member.java#L23
- [x] ConcertMember https://github.com/cau-rubato/rubato-backend/blob/7e0e25634c53e5a9f80e813643bdb8c05f17bd46/src/main/java/org/rubatophil/www/api/domain/mapping/concertMember/ConcertMember.java#L22

---

# 2. Test Case
_해당사항 없음_

---

# 3. 유의사항
_해당사항 없음_
