### ISSUE TITLE
[Domain] Apply, ApplyCampaign 수정 및 테스트 코드 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#34]
# 1. TODO

## 1.1. Apply
- [x] `Setter` 설정 필드 제한
- [x] `Constructor` 생성
- [x] `Constructor`로 `Builder` 생성
- [x] `@NoArgsConstructor` 어노테이션 추가 후 `AccessLevel.PROTECTED` 설정
- [x] 연관관계 필드 `@NotNull` 제거
- [x] `ApplyCampaign`과의 연관관계를 `@ManyToOne`으로 설정
- [x] `setApplicant()` 메서드 재정의

## 1.2. ApplyCampaign
- [x] `Setter` 설정 필드 제한
- [x] `Constructor` 생성
- [x] `Constructor`로 `Builder` 생성
- [x] `@NoArgsConstructor` 어노테이션 추가 후 `AccessLevel.PROTECTED` 설정
- [x] 연관관계 필드 `@NotNull` 제거
- [x] `Apply`와의 연관관계를 `@OneToMany`로 설정
- [x] `addApply()` 메서드 생성

---

# 2. Test Case
## 2.1. Apply
- [x] `PrePersist` 테스트
- [x] `Builder` 테스트
- [x] `setApplicant()` 테스트

## 2.2. ApplyCampaign
- [x] `PrePersist` 테스트
- [x] `Builder` 테스트
- [x] `addApply()` 테스트

---

# 3. 유의사항
- `Setter`와 `Builder`는 허용할 필드를 잘 고려해서 넣을 것.
  - 이미 초기화되고, 불변값을 가지는 필드는 `Builder` 허용하지 않음.
  - 수정하면 안되는 필드에 대해서 `Setter`허용하지 않음.
  - 이 외 필드의 특성에 따라 잘 판단하여 `Setter`, `Builder`를 허용하지 결정
- add 메서드는 연관관계 양쪽 클래스 모두 업데이트 해야함.
- remove 메서드는 이후 비즈니스 로직에서 필요시 정의
