### ISSUE TITLE
[Domain] FAQ엔티티 수정 및 Test Code 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#35]
# 1. TODO
- [x] Setter 제한
- [x] Constructor에 Builder 설정
- [x] @NoArgsConstructor 에 access를 `AccesLevel.PROTECTED`로 설정

---

# 2. Test Case
- [x] FAQRepository 테스트를 domain/FAQTest 로 변경
- [x] FAQ 변경사항에 맞게 테스트 코드 수정
---

# 3. 유의사항
- 없음
