### ISSUE TITLE
[Domain] Donate, Budget 엔티티 수정 및 Test Code 작성

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#39]
# 1. TODO
## 1.1. Donate
- [ ] Setter 설정 필드 제한
- [ ] Constructor 생성
- [ ] Constructor로 Builder 생성
- [ ] @NoArgsConstructor 어노테이션 추가 후 `AccessLevel.PROTECTED` 설정
- [ ] 연관관계 필드 @NotNull 제거
- [ ] addDonateBudget() 메서드 생성

## 1.2. Budget
- [ ] Setter 설정 필드 제한
- [ ] Constructor 생성
- [ ] Constructor로 Builder 생성
- [ ] @NoArgsConstructor 어노테이션 추가 후 `AccessLevel.PROTECTED` 설정
- [ ] 연관관계 필드 @NotNull 제거
- [ ] addDonateBudget() 메서드 생성

---

# 2. Test Case
#2.1. Donate
- [ ] Builder 테스트
- [ ] addDonateBudget() 테스트

#2.2. Budget
- [ ] Builder 테스트
- [ ] addDonateBudget() 테스트

---

# 3. 유의사항
- Setter와 Builder는 허용할 필드를 잘 고려해서 넣을 것.
  - 이미 초기화되고, 불변값을 가지는 필드는 Builder 허용하지 않음.
  - 수정하면 안되는 필드에 대해서 Setter허용하지 않음.
  - 이 외 필드의 특성에 따라 잘 판단하여 Setter, Builder를 허용하지 결정
- add 메서드는 연관관계 양쪽 클래스 모두 업데이트 해야함.
- remove 메서드는 이후 비즈니스 로직에서 필요시 정의
