### ISSUE TITLE
[Domain] 소개 페이지 Entity

### ISSUE THREAD

**Issue by AllyHyeseongKim** [cau-rubato/rubato-backend#4]
# 1. TODO
- [x]  Entity Table name 수정
- [x]  Entity column name 수정
- [x]  Database UML 생성
- [x]  Domain Package 생성
- [x]  지원하기 Entity 생성
- [x]  후원하기 Entity 생성
- [x]  정기연주회 Entity 생성
- [x]  Member Entity 생성
- [x]  계정 Entity 생성
- [x]  FAQ Entity 생성

---

# 2. Test Case
- _해당사항 없음_

---

# 3. 유의사항
- **Entity Table name**은 모두 `대문자`로 한다.
- **Entity Table**, **Column name**은 모두 `snake_case`로 한다.
