### ISSUE TITLE
[Controller] FAQ List 제공하는 기능 개발

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#7]
# 1. TODO
- [x] POST - FAQ를 insert하는 endpoint
- [x] GET - FAQ List를 반환하는 endpoint
- [x] FAQ List를 공급하는 Service
- [x] FAQ table에서 데이터 가져오는 Repository

---

# 2. Test Case
## 2.1. FAQControllerTest
- [x] Service를 Mocking하여 입력 데이터에 따라 올바른 데이터가 반환되는지 MockMvc를 이용해 성공 테스트
- [x] 위 환경에서 실패 테스트

## 2.2. FAQServiceTest
- [x] Mock FAQRepsository에 대해 올바른 데이터를 return 하는지 테스트

---

# 3. 유의사항
- id, title, detail 형태의 json 반환.
- Jackson이용
