### ISSUE TITLE
[Controller] 지원 정보 제공 및 지원서 수렴 기능 개발

### ISSUE THREAD

**Issue by bkRyusim** [cau-rubato/rubato-backend#9]
# 1. TODO
- [ ] ApplyController 생성
- [ ] ApplyCampaign Entity 생성 : 모집기수, 모집기간, 모집 상태
- [ ] 지원 기간 제공하는 endpoint
- [ ] 지원서 수렴하는 endpoint(임시저장, 최종제출)
- [ ] 지원 기능 구현한 Service
- [ ] 지원서 데이터 생성 및 조회하는 Repository 

---

# 2. Test Case
## 2.1.  ApplyControllerTest
- [ ] MockMvc 이용해 올바른 지원기간 표시되는지 테스트
- [ ] 지원 정보 받아서 Service잘 호출하고 결과 반환하는지 테스트

## 2.2. ApplyServiceTest
- [ ] 지원 기간을 잘 반환하는지 테스트
- [ ] 지원 정보를 잘 저장하는지 테스트
- [ ] 실패 테스트

## 2.3. ApplyRepositoryTest
- [ ] 데이터 잘 조회하는지 테스트
- [ ] 데이터가 잘 들어갔는지 테스트
- [ ] 실패 테스트

## 2.4. ApplyCampaignRepositoryTest
- [ ] 데이터 잘 조회하는지 테스트
- [ ] 실패 테스트

---

# 3. 유의사항
- Notion 문서 참고하여 개발
